name:                coordinator
version:             0.1.0.0
github:              "ashutoshrishi/websocket-games"
license:             BSD3
author:              "Rishi Ranjan"
maintainer:          "arishiranjan@gmail.com"
copyright:           "2019 Rishi Ranjan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ashutoshrishi/websocket-games#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- text
- websockets

library:
  source-dirs: src

executables:
  coordinator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coordinator

tests:
  coordinator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coordinator
